name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: Goodbye World
        run: echo "Goodbye World"
        shell: bash

      - name: SSH into EC2 and print logs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Running Hello World on EC2"
            cd ${{ secrets.TARGET_DIR }}
            git pull origin main
            # Add any other necessary commands here
            cat logs-of-your-job.txt  # Assuming your job logs are stored in a file


