name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest

    steps:
      - name: Goodbye World
        run: echo "Goodbye World"
        shell: bash


